Description: AWS CloudFormation template for vroom resources

Parameters:
  SNSEmail:
    Description: Email to receive SNS alerts
    Type: String
  
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.1.0/21
      Tags:
        - Key: Application
          Value: vroom
        - Key: Name
          Value: hub01

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: 10.10.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Application
          Value: vroom
        - Key: Name
          Value: subnet01

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      CidrBlock: 10.10.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Application
          Value: vroom
        - Key: Name
          Value: subnet02

  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 2, !GetAZs "" ]
      CidrBlock: 10.10.3.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Application
          Value: vroom
        - Key: Name
          Value: subnet03

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: 10.10.4.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Application
          Value: vroom
        - Key: Name
          Value: subnet04

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      CidrBlock: 10.10.5.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Application
          Value: vroom
        - Key: Name
          Value: subnet05

  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 2, !GetAZs "" ]
      CidrBlock: 10.10.6.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Application
          Value: vroom
        - Key: Name
          Value: subnet06

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
        - Key: Application
          Value: vroom
        - Key: Name
          Value: hub01

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Default security group for vroom
      GroupName: vroom
      SecurityGroupEgress: 
        - Egress
      SecurityGroupIngress: 
        - Ingress
      Tags: 
        - Key: Application
          Value: vroom
      VpcId: !Ref VPC

  # Default SNS topic for vroom services
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: vroom
      Tags: 
        - Key: Application
          Value: vroom
      TopicName: vroom

  # Default SNS email subscription for vroom notifications
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref SNSEmail
      Protocol: email
      TopicArn: !GetAtt SNSTopic.TopicArn
  
  # S3 table Bucket to serve as the database
  TableBucket:
    Type: AWS::S3Tables::TableBucket
    Properties:
      EncryptionConfiguration: 
        SSEAlgorithm: AES256
      TableBucketName: vroom
      UnreferencedFileRemoval: 
          NoncurrentDays: 1
          Status: Enabled
          UnreferencedDays: 1